# Generated by Django 5.0.2 on 2024-06-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='descripcion',
            field=models.CharField(default='SOME STRING', max_length=250),
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.ImageField(upload_to='juegos'),
        ),
    ]
